apiVersion: v1
kind: Service
metadata:
  labels:
    component: elastic
  name: elasticsearch
  namespace: my-proj
spec:
  ports:
    - name: 9200-tcp
      port: 9200
      protocol: TCP
      targetPort: 9200
  selector:
    component: elastic
  type: ClusterIP
  
 ########################################################################################################################### 
  
  
apiVersion: v1
kind: Service
metadata:
  labels:
    component: elastic
  name: elasticsearch-2
  namespace: my-proj
spec:
  ports:
    - name: 9200-tcp
      port: 9200
      protocol: TCP
      targetPort: 9200
  selector:
    component: elastic
  type: NodePort
