apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: '2022-09-06T10:54:57Z'
  labels:
    app: tomcat
  name: tomcat-node
  namespace: my-proj
  resourceVersion: '352817'
  selfLink: /api/v1/namespaces/my-proj/services/tomcat-node
  uid: 58b3fc75-2dd2-11ed-b99a-0050569e5632
spec:
  clusterIP: 172.30.1.120
  externalTrafficPolicy: Cluster
  ports:
    - name: 8080-tcp
      nodePort: 32215
      port: 8081
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: tomcat
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
